### ISSUE TITLE
RHEL 8 AWS workshop: Change to use of aws.create role breaks deployment in region ap-southeast 2

### ISSUE THREAD

**Issue by benblasco** [RedHatGov/redhatgov.workshops#173]
The following change has removed previous commits which had added support for deploying the RHEL 8 workshop into AWS region ap-southeast-2.  The previous commits can be seen here.

https://github.com/RedHatGov/redhatgov.workshops/commit/316430177b508506fb6292976a5845de4f208e2b#diff-d1d8121193f65fab18245bee99530f6533cd7e9744306eb42e93a7424e4314ae

These changes were originally added to PR [162](https://github.com/RedHatGov/redhatgov.workshops/pull/162) and have been lost by the change in this commit.  

I may need some advice on fixing this @ajacocks ?  We may need to go back and do a diff between the now deleted aws.create role in this workshop and the version it refers to now.  I will separately make the appropriate code changes for this week's workshop to run in ap-southeast-2 in a branch on my own fork.

**Comment by benblasco** [comment]
Here is the lost code I need to restore, but we may need to investigate further:

```
[bblasco@nuc redhatgov.workshops.20211111.working]$ diff rhel_aws/roles/aws.create/defaults/main.yml ../redhatgov.workshops/ansible_tower_aws/roles/aws.create/defaults/main.yml 
3a4,17
> #-----------------------------------------------------------------------------
> # instance_storage
> rhel_instance_vols: []
> #  - device_name:                  "/dev/sdf"  # startes with sdf
> #    volume_size:                  50          # gigabytes
> #    volume_type:                  "gp3"       # aws device type
> #    delete_on_termination:        "true"      # delete with the instance
> 
> # defaults for workshop settings
> admin_rhel_count:     1
> student_count:        2
> student_nodes_count:  1
> force_dns:            "no"
> 
27,39d40
<   ap-southeast-2:
<     rhel6:
<       # ami: "ami-0fcbf553f091053d7" # RHEL-6.10_HVM-20190524-x86_64-0-Hourly2-GP2 NOT AVAILABLE IN THIS REGION
<     rhel7:
< #      ami: "ami-04268981d7c33264d" # RHEL-7.5_HVM-20180813-x86_64-0-Access2-GP2
<       ami: "ami-864971e3" # RHEL-7.5_HVM_GA-JBEAP-7.1.2-20180629-x86_64-1-Access2-GP2 NOT AVAILABLE IN THIS REGION
<     rhel8:
< #      ami: "ami-0b2821bf4a7dba483" # RHEL-8.0_HVM-20190920-x86_64-0-Access2-GP2
< #      ami: "ami-0a54aef4ef3b5f881" # RHEL-8.2.0_HVM-20200423-x86_64-0-Hourly2-GP2 NOT AVAILABLE IN THIS REGION
<       ami: "ami-0810abbfb78d37cdf" # RHEL-8.2.0_HVM-20200423-x86_64-0-Hourly2-GP2 NOT AVAILABLE IN THIS REGION
<     win2016:
< #      ami: "ami-08b4a0f6e106c1dba" # Windows_Server-2016-English-Full-Base-2019.02.13 NOT AVAILABLE IN THIS REGION
<       ami: "ami-03808957a3743a18c" # Windows_Server-2016-English-Full-Base-2021.07.14 UNTESTED
41d41
< ...

```

**Comment by benblasco** [comment]
You can find my branch with proposed changes here:

[](https://github.com/benblasco/redhatgov.workshops/commits/bblasco_rhel8_202111b/rhel_aws)

**Comment by ajacocks** [comment]
Your fix was good. Merged and thanks!
