### ISSUE TITLE
Move ansible roles to new roles directory in the repo

### ISSUE THREAD

**Issue by ajacocks** [RedHatGov/redhatgov.workshops#35]
I'm planning to move all the roles, that have general use, to a directory called 'roles', in this repo.  After reading up on Git submodules, and all the issues with them, that seems to be the best path.

If we decide to split them off into their own repo later, it's fairly easy to do.  Please comment soon, as I plan to make the changes this week.

**Comment by jaredhocutt** [comment]
Avoiding Git submodules is the right thing to do. I think having a common roles directory is the right solution for this repo.

In the future, if you want to split roles out, you can create a repo per role and use Ansible requirements.yml.

http://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#installing-multiple-roles-from-a-file

**Comment by ajacocks** [comment]
Cosed by PR #38
