### ISSUE TITLE
Don't use underscore "_" in the workshop name.

### ISSUE THREAD

**Issue by mshoger** [RedHatGov/redhatgov.workshops#56]
Ran into this today with a workshop - there's a known issue with Apache and underscores in the workshop name portion of the machine name. If you try to hit the web page you get an error 400. If you use the public facing IP address, it works fine.

This line:

workshop_prefix  : defaults to "tower", set to the name of your workshop

should say:

workshop_prefix  : defaults to "tower", set to the name of your workshop - NO underscores!

I have changed the file and submitted it.

**Comment by mshoger** [comment]
Note that this applied to the Ansible Tower workshop, but others might be impacted as well.

**Comment by dmc5179** [comment]
@ajacocks This update appears to have been applied. Can this issue be closed or do we need to check if this is effecting other workshops?

**Comment by ajacocks** [comment]
Yep, let's close.
